credentials:
  usernames:
    admin:
      email: yli1027@126.com
      name: Administrator
      password: $2b$12$OKeMX9HHZzBHNjYg76XoROsq9NFjZA.IYZE1psarG4XiGJwFXLG66
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
pre-authorized:
  emails:
  - test@gmail.com